---
- hosts: Cisco
  gather_facts: false

  tasks:
    - name: Output device information
      ansible.netcommon.cli_parse:
        command: show version
        parser:
          name: ansible.netcommon.native
        set_fact: version

    - debug:
        var: version
