---
- hosts: Cisco
  gather_facts: false

  tasks:
    - name: Output device information
      ansible.netcommon.cli_parse:
        command: show version
        parser:
          name: ansible.netcommon.native
        set_fact: version

    - debug:
        var: version
        
  tasks:
    - name: Output device information
      ansible.netcommon.cli_parse:
        command: show interfaces
        parser:
          name: ansible.netcommon.native
        set_fact: interfaces_fact

    - debug:
        var: interfaces
