---
- hosts: Cisco
  gather_facts: false

  tasks:
    - name: Output device information
      ansible.netcommon.cli_parse:
        command: show version
        parser:
          name: ansible.netcommon.native
        set_fact: version

    - debug:
        var: version
        
    - name: Output interface type
      ansible.netcommon.cli_parse:
        command: show interfaces
        parser:
          name: ansible.netcommon.native
        set_fact: interface_type

    - debug:
        var: interface_type
